name: plantalgo
description: AI-powered crop disease diagnosis mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  image_picker: ^1.0.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  provider: ^6.1.1
  image: ^4.1.3
  path_provider: ^2.1.1
  flutter_chat_ui: ^2.5.2
  flutter_chat_types: ^3.6.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/